name = "fixtweet"
account_id = "1aa8d529af2739a1e090b8c52c7145b5"
main = "./dist/worker.js"
compatibility_date = "2024-11-14"
send_metrics = false

# Remove this if not using Cloudflare Analytics Engine
# analytics_engine_datasets = [
#   { binding = "AnalyticsEngine" }
# ]

# Remove this if not using elongator account proxying
# services = [
#   { binding = "TwitterProxy", service = "elongator" }
# ]

[build]
command = "npm run build"
